Домашка к уроку 8
eugene-okulik/Smillyhamster pull request #10
Opened 2024-04-14 11:10 UTC by alko-tester

2024-04-15 08:45 UTC, eugene-okulik requested changes

2024-04-15 08:45 UTC, eugene-okulik commented on homework/name_secondname/homework_8/homework_8_task_2.py
> +print("Стотысячное число из списка Фибоначи: \n", list(fib(100000))[-1])
Последовательность фибоначчи - бесконечная. Твой генератор сделан не бесконечным, поэтому его результат ты можешь поместить в список, но если бы он был бесконечным, список из него сделать бы не получилось.  
Но и сейчас список получается огромный и ты задействуешь очень много ресурсов для того, чтобы выполнить довольно простую операцию. Генераторы существуют для того, чтобы не приходилось хранить огромные массивы данных в одной переменной.  
Со значениями, выдаваемыми генератором, обычно работают с помощью циклов.

2024-04-15 09:08 UTC, alko-tester commented on homework/name_secondname/homework_8/homework_8_task_2.py
> +print("Стотысячное число из списка Фибоначи: \n", list(fib(100000))[-1])
Ок, понял. Вечером постараюсь переделать

2024-04-18 11:17 UTC, eugene-okulik approved these changes

2024-04-18 11:17 UTC, eugene-okulik commented on homework/name_secondname/homework_8/homework_8_task_1.py
> +        break
:+1:

2024-04-18 11:17 UTC, eugene-okulik commented on homework/name_secondname/homework_8/homework_8_task_1.py
> +def fib(limit=100001):
Ага, только забыл слово limit убрать. ))  
Выглядит как не бесконечная, но ты этим лимитом не пользуешься.

2024-04-18 11:17 UTC, merged